# Generated by Django 6.0.5 on 2026-05-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfeeling',
            old_name='muscele_soreness',
            new_name='muscle_soreness',
        ),
    ]
