# Generated by Django 6.0.5 on 2026-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_rename_muscele_soreness_dailyfeeling_muscle_soreness'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendation', models.TextField()),
                ('user_followed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
