# Generated by Django 6.0.5 on 2026-06-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_coachrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyfeeling',
            options={'ordering': ['-created_at']},
        ),
    ]
