# Generated by Django 6.0.5 on 2026-06-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_alter_dailyfeeling_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachrecommendation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dailyfeeling',
            options={'ordering': ['-date']},
        ),
    ]
