# Generated by Django 6.0.5 on 2026-06-06 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_alter_coachrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='coachrecommendation',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coachrecommendation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
