# Generated by Django 6.0.5 on 2026-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_coachrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfeeling',
            name='notes',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('general_health', 'General Health')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='injury',
            name='body_part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
