# Generated by Django 6.0.5 on 2026-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfeeling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
