# Generated by Django 6.0.5 on 2026-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_syncstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(max_length=60)),
                ('input_tokens', models.IntegerField(default=0)),
                ('cache_creation_tokens', models.IntegerField(default=0)),
                ('cache_read_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('api_calls', models.IntegerField(default=1)),
                ('tools_used', models.CharField(blank=True, default='', max_length=255)),
                ('user_message', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
