# Generated by Django 6.0.5 on 2026-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_plannedsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedsession',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
