# Generated by Django 6.0.5 on 2026-06-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_plannedsession_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiusage',
            name='tools_used',
        ),
    ]
