# Generated by Django 6.0.5 on 2026-06-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_remove_apiusage_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='tools_used',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
