# Generated by Django 6.0.5 on 2026-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_apiusage_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
