# Generated by Django 6.0.5 on 2026-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_apiusage_prompt_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='config_version',
            field=models.CharField(blank=True, default='baseline', max_length=40),
        ),
    ]
