# Generated by Django 6.0.5 on 2026-07-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_apiusage_config_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='final_text',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='apiusage',
            name='tool_trace',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
