# Generated by Django 6.0.5 on 2026-08-05 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_apiusage_final_text_apiusage_tool_trace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='coach.plannedsession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
