# Generated by Django 6.0.5 on 2026-08-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_plannedexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusage',
            name='round_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
