# Generated by Django 6.0.5 on 2026-05-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_id', models.CharField(max_length=64, unique=True)),
                ('date', models.DateField()),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.FloatField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('avg_hr', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('training_load', models.FloatField(blank=True, null=True)),
                ('training_effect_aerobic', models.FloatField(blank=True, null=True)),
                ('training_effect_anaerobic', models.FloatField(blank=True, null=True)),
                ('avg_cadence', models.IntegerField(blank=True, null=True)),
                ('avg_stride_length', models.FloatField(blank=True, null=True)),
                ('ground_contact_time', models.FloatField(blank=True, null=True)),
                ('vertical_oscillation', models.FloatField(blank=True, null=True)),
                ('avg_running_power', models.FloatField(blank=True, null=True)),
                ('avg_power', models.IntegerField(blank=True, null=True)),
                ('normalized_power', models.IntegerField(blank=True, null=True)),
                ('tss', models.FloatField(blank=True, null=True)),
                ('intensity_factor', models.FloatField(blank=True, null=True)),
                ('avg_pace_min_per_km', models.FloatField(blank=True, null=True)),
                ('elevation_gain_m', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('body_battery_high', models.IntegerField(blank=True, null=True)),
                ('body_battery_low', models.IntegerField(blank=True, null=True)),
                ('stress_level_avg', models.IntegerField(blank=True, null=True)),
                ('training_readiness_score', models.IntegerField(blank=True, null=True)),
                ('training_readiness_label', models.CharField(blank=True, max_length=50, null=True)),
                ('training_status', models.CharField(blank=True, choices=[('peaking', 'Peaking'), ('productive', 'Productive'), ('maintaining', 'Maintaining'), ('recovery', 'Recovery'), ('unproductive', 'Unproductive'), ('overreaching', 'Overreaching'), ('detraining', 'Detraining')], max_length=20, null=True)),
                ('recovery_time_hours', models.IntegerField(blank=True, null=True)),
                ('vo2max', models.FloatField(blank=True, null=True)),
                ('endurance_score', models.FloatField(blank=True, null=True)),
                ('total_calories_burned', models.IntegerField(blank=True, null=True)),
                ('active_calories', models.IntegerField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HRVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('hrv_rmssd', models.FloatField(blank=True, null=True)),
                ('hrv_status', models.CharField(blank=True, choices=[('balanced', 'Balanced'), ('low', 'Low'), ('poor', 'Poor'), ('unbalanced', 'Unbalanced')], max_length=20, null=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('deep_sleep_hours', models.FloatField(blank=True, null=True)),
                ('rem_sleep_hours', models.FloatField(blank=True, null=True)),
                ('light_sleep_hours', models.FloatField(blank=True, null=True)),
                ('awake_hours', models.FloatField(blank=True, null=True)),
                ('body_battery_change', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_watts', models.IntegerField(blank=True, null=True)),
                ('max_hr', models.IntegerField(blank=True, null=True)),
                ('lthr', models.IntegerField(blank=True, null=True)),
                ('primary_sport', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
