# Generated by Django 6.0.5 on 2026-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(unique=True)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('precipitation_probability', models.IntegerField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('cloud_cover', models.IntegerField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('is_day', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
