# Generated by Django 6.0.5 on 2026-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_weatherhourly'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('muscele_soreness', models.IntegerField(blank=True, null=True)),
                ('motivation', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('general_health', 'General Health')], max_length=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_resolved', models.DateField()),
                ('body_part', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('affects_running', models.BooleanField(blank=True, default=True, null=True)),
                ('affects_cycing', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
