# Generated by Django 6.0.5 on 2026-05-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_dailyfeeling_goal_injury'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyfeeling',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='injury',
            options={'ordering': ['-date_started']},
        ),
        migrations.AddField(
            model_name='dailyfeeling',
            name='muscle_sore',
            field=models.CharField(blank=True, choices=[('hamstrongs', 'Hamstrings'), ('quads', 'Quads'), ('calves', 'Calves'), ('glutes', 'Glutes'), ('lower_back', 'Lower Back'), ('upper_back', 'Upper Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core')], max_length=100, null=True),
        ),
    ]
