# Generated by Django 6.0.5 on 2026-05-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_dailyfeeling_options_alter_injury_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injury',
            old_name='affects_cycing',
            new_name='affects_cycling',
        ),
        migrations.AlterField(
            model_name='injury',
            name='date_resolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
