# Generated by Django 6.0.5 on 2026-05-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_rename_affects_cycing_injury_affects_cycling_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyFeeling',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Injury',
        ),
    ]
