# Generated by Django 6.0.5 on 2026-06-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_delete_dailyfeeling_delete_goal_delete_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='athlete_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injury_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
