# Generated by Django 6.0.5 on 2026-06-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_userprofile_athlete_notes_userprofile_injury_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='fitness_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
