# Generated by Django 6.0.5 on 2026-06-07 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0008_dailystats_fitness_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailystats',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily Stats'},
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='training_readiness_score',
        ),
        migrations.AddField(
            model_name='dailystats',
            name='acwr_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailystats',
            name='endurance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='training_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
