# Generated by Django 6.0.5 on 2026-06-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0010_ftprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystats',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
