# Generated by Django 6.0.5 on 2026-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_dailystats_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorCyclingTrenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('IF', models.FloatField()),
                ('TSS', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['TSS'],
            },
        ),
    ]
