# Generated by Django 6.0.5 on 2026-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_indoorcyclingtrenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndoorCyclingWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('recovery', 'Recovery'), ('endurance', 'Endurance'), ('tempo', 'Tempo'), ('sweetspot', 'Sweet Spot'), ('threshold', 'Threshold'), ('vo2max', 'VO2 Max'), ('anaerobic', 'Anaerobic'), ('testing', 'Testing')], max_length=50)),
                ('duration_min', models.IntegerField()),
                ('intensity_factor', models.FloatField()),
                ('tss', models.FloatField()),
                ('description', models.TextField(blank=True, default='')),
                ('structure', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='mywhoosh', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tss'],
            },
        ),
        migrations.DeleteModel(
            name='IndoorCyclingTrenings',
        ),
    ]
