# Generated by Django 6.0.5 on 2026-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0013_indoorcyclingworkout_delete_indoorcyclingtrenings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indoorcyclingworkout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='indoorcyclingworkout',
            name='source',
        ),
        migrations.AlterField(
            model_name='indoorcyclingworkout',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
