# Generated by Django 6.0.5 on 2026-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0014_remove_indoorcyclingworkout_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('legs', 'Legs'), ('upper', 'Upper Body'), ('core', 'Core'), ('posterior_chain', 'Posterior Chain'), ('mobility', 'Mobility')], max_length=30)),
                ('target_muscle', models.CharField(blank=True, default='', max_length=100)),
                ('equipment', models.CharField(blank=True, default='', max_length=100)),
                ('default_sets', models.IntegerField(blank=True, null=True)),
                ('default_reps', models.IntegerField(blank=True, null=True)),
                ('progression_notes', models.TextField(blank=True, default='')),
                ('injury_notes', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
