#!/usr/bin/env python3
"""Build the compact session catalog from leaf frontmatter.

This is the "index always" half of progressive disclosure: a one-line-per-
session summary carrying the scheduling metadata (load axes, recovery,
same-day conflicts) so a week can be shortlisted and conflict-checked without
reading a single leaf body.

Usage:
    python catalog.py            # compact index, one line per session
    python catalog.py --markdown # regenerate reference/catalog.md
"""
import sys

from frontmatter import SKILL_ROOT, iter_sessions, use_utf8_stdout

_AXES = ("neural", "mechanical", "metabolic", "damage")


def _axis_str(load):
    return "/".join(f"{a[:4]}:{load.get(a, '?')}" for a in _AXES)


def index_lines():
    lines = []
    for session_id, meta, _ in iter_sessions():
        load = meta.get("load", {})
        conflicts = ",".join(meta.get("same_day_conflicts", [])) or "none"
        lines.append(
            f"{session_id} — {meta.get('description', '')} "
            f"[{_axis_str(load)}; recovery {meta.get('residual_fatigue_h', '?')}h; "
            f"same-day conflicts: {conflicts}]"
        )
    return lines


def markdown_table():
    rows = [
        "# Session catalog",
        "",
        "> Generated by `scripts/catalog.py --markdown` from leaf frontmatter.",
        "> Do not edit by hand — edit the session files and regenerate.",
        "",
        "| Session | Load (neur/mech/meta/dmg) | Recovery | Same-day conflicts | Use when |",
        "|---|---|---|---|---|",
    ]
    for session_id, meta, _ in iter_sessions():
        load = meta.get("load", {})
        axes = "/".join(str(load.get(a, "?")) for a in _AXES)
        conflicts = ", ".join(meta.get("same_day_conflicts", [])) or "—"
        desc = meta.get("description", "")
        rows.append(
            f"| `{session_id}` | {axes} | {meta.get('residual_fatigue_h', '?')}h "
            f"| {conflicts} | {desc} |"
        )
    return "\n".join(rows) + "\n"


def main(argv):
    use_utf8_stdout()
    if "--markdown" in argv:
        out = SKILL_ROOT / "reference" / "catalog.md"
        out.write_text(markdown_table(), encoding="utf-8")
        print(f"wrote {out.relative_to(SKILL_ROOT)}")
        return 0
    for line in index_lines():
        print(line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
