# Run with:  python manage.py sync_exercises

from django.core.management.base import BaseCommand
from sync.models import Exercise


EXERCISES = [
    # ---- legs ----
    {
        "name": "Barbell Back Squat",
        "category": "legs",
        "target_muscle": "quads, glutes",
        "equipment": "barbell, rack",
        "default_sets": 4,
        "default_reps": 6,
        "progression_notes": "Add 2.5kg per week while form holds; deload 10% every 4th week.",
        "injury_notes": "Avoid with acute knee pain; substitute Leg Press or Box Squat to a higher box to reduce knee flexion.",
        "description": "Primary lower-body strength movement.",
    },
    {
        "name": "Romanian Deadlift",
        "category": "posterior_chain",
        "target_muscle": "hamstrings, glutes, lower back",
        "equipment": "barbell",
        "default_sets": 3,
        "default_reps": 8,
        "progression_notes": "Progress load only once full ROM with a flat back is consistent; hamstring length matters more than weight here.",
        "injury_notes": "Avoid with acute lower-back flare-up; substitute Cable Pull-Through (less spinal load).",
        "description": "Hip-hinge hamstring/glute builder, key for cycling posterior chain strength.",
    },
    {
        "name": "Bulgarian Split Squat",
        "category": "legs",
        "target_muscle": "quads, glutes",
        "equipment": "dumbbells, bench",
        "default_sets": 3,
        "default_reps": 10,
        "progression_notes": "Progress via dumbbell weight before adding reps past 12.",
        "injury_notes": "Avoid with acute knee pain on the front leg; substitute Leg Press (bilateral, less unilateral knee shear).",
        "description": "Unilateral quad/glute exercise, exposes side-to-side strength imbalances.",
    },
    {
        "name": "Leg Press",
        "category": "legs",
        "target_muscle": "quads, glutes",
        "equipment": "leg press machine",
        "default_sets": 4,
        "default_reps": 10,
        "progression_notes": "Add load in small increments; machine-guided so easier to progress safely than free-weight squats.",
        "injury_notes": "Knee-friendlier than Back Squat — good substitute during a knee flare-up if pain-free through range.",
        "description": "Machine-based quad/glute builder, lower technical demand than a barbell squat.",
    },
    {
        "name": "Nordic Hamstring Curl",
        "category": "posterior_chain",
        "target_muscle": "hamstrings",
        "equipment": "partner or footpad anchor",
        "default_sets": 3,
        "default_reps": 5,
        "progression_notes": "Progress by increasing eccentric control/ROM before adding assistance-band removal.",
        "injury_notes": "Stop immediately on hamstring twinge; regress to Slow Eccentric Leg Curl on a machine instead.",
        "description": "Eccentric hamstring strengthener, strong injury-prevention evidence for running/cycling athletes.",
    },
    {
        "name": "Walking Lunge",
        "category": "legs",
        "target_muscle": "quads, glutes",
        "equipment": "dumbbells (optional)",
        "default_sets": 3,
        "default_reps": 12,
        "progression_notes": "Add dumbbell load before adding distance.",
        "injury_notes": "Avoid with acute knee pain; substitute Leg Press.",
        "description": "Unilateral, dynamic quad/glute exercise with a balance component.",
    },
    {
        "name": "Calf Raise",
        "category": "legs",
        "target_muscle": "calves",
        "equipment": "step or machine",
        "default_sets": 3,
        "default_reps": 15,
        "progression_notes": "Progress reps to 20 before adding load.",
        "injury_notes": "Reduce ROM if Achilles is irritable.",
        "description": "Calf/Achilles strength and running-economy support.",
    },
    # ---- upper ----
    {
        "name": "Bench Press",
        "category": "upper",
        "target_muscle": "chest, triceps, shoulders",
        "equipment": "barbell, bench",
        "default_sets": 4,
        "default_reps": 6,
        "progression_notes": "Add 1.25-2.5kg per week; deload if bar speed slows noticeably.",
        "injury_notes": "Avoid with acute shoulder pain; substitute Dumbbell Floor Press (reduced ROM).",
        "description": "Primary upper-body pressing strength movement.",
    },
    {
        "name": "Overhead Press",
        "category": "upper",
        "target_muscle": "shoulders, triceps",
        "equipment": "barbell or dumbbells",
        "default_sets": 3,
        "default_reps": 8,
        "progression_notes": "Progress slowly — shoulders respond better to volume than heavy singles.",
        "injury_notes": "Avoid with acute shoulder impingement; substitute Landmine Press (more shoulder-friendly angle).",
        "description": "Shoulder/triceps pressing strength.",
    },
    {
        "name": "Barbell Row",
        "category": "upper",
        "target_muscle": "lats, upper back, biceps",
        "equipment": "barbell",
        "default_sets": 4,
        "default_reps": 8,
        "progression_notes": "Add load once strict form (no lower-back swing) is consistent.",
        "injury_notes": "Avoid with acute lower-back flare-up; substitute Chest-Supported Row.",
        "description": "Horizontal pulling strength, balances pressing volume.",
    },
    {
        "name": "Pull-Up",
        "category": "upper",
        "target_muscle": "lats, biceps",
        "equipment": "pull-up bar",
        "default_sets": 3,
        "default_reps": 8,
        "progression_notes": "Progress via assistance-band removal, then added weight once 3x10 bodyweight is achieved.",
        "injury_notes": "Avoid with acute elbow/wrist pain; substitute Lat Pulldown.",
        "description": "Vertical pulling strength.",
    },
    {
        "name": "Lat Pulldown",
        "category": "upper",
        "target_muscle": "lats, biceps",
        "equipment": "cable machine",
        "default_sets": 3,
        "default_reps": 10,
        "progression_notes": "Machine-guided, safe to progress load steadily week to week.",
        "injury_notes": "Good substitute for Pull-Up during wrist/elbow flare-ups.",
        "description": "Vertical pulling strength, easier to load precisely than Pull-Up.",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "category": "upper",
        "target_muscle": "shoulders, triceps",
        "equipment": "dumbbells",
        "default_sets": 3,
        "default_reps": 10,
        "progression_notes": "Progress load once full ROM is pain-free and controlled both directions.",
        "injury_notes": "Reduce ROM (press to forehead height, not full lockout overhead) with shoulder impingement.",
        "description": "Unilateral-capable shoulder press, more shoulder-friendly than barbell OHP for some athletes.",
    },
    # ---- core ----
    {
        "name": "Plank",
        "category": "core",
        "target_muscle": "core, shoulders",
        "equipment": "none",
        "default_sets": 3,
        "default_reps": None,
        "progression_notes": "Progress hold time (30s increments) before adding load on the back.",
        "injury_notes": "Generally safe with most injuries; drop to a shorter hold if lower-back pain appears.",
        "description": "Anti-extension core stability, direct carryover to cycling/running posture.",
    },
    {
        "name": "Pallof Press",
        "category": "core",
        "target_muscle": "obliques, core",
        "equipment": "cable or band",
        "default_sets": 3,
        "default_reps": 12,
        "progression_notes": "Progress band/cable resistance once form (no rotation) is solid.",
        "injury_notes": "Safe with most lower-back injuries — anti-rotation, low spinal load.",
        "description": "Anti-rotation core stability.",
    },
    {
        "name": "Copenhagen Plank",
        "category": "core",
        "target_muscle": "adductors, core",
        "equipment": "bench",
        "default_sets": 3,
        "default_reps": None,
        "progression_notes": "Progress from bent-knee to straight-leg variation before adding hold time.",
        "injury_notes": "Direct groin/adductor-strain prevention exercise; stop on any adductor pain, don't push through.",
        "description": "Adductor strength — key injury-prevention exercise for cycling and skating.",
    },
    {
        "name": "Dead Bug",
        "category": "core",
        "target_muscle": "core",
        "equipment": "none",
        "default_sets": 3,
        "default_reps": 10,
        "progression_notes": "Progress from bent-knee taps to straight-leg lowers.",
        "injury_notes": "Very lower-back-friendly — good starting point returning from a back flare-up.",
        "description": "Anti-extension core control, low spinal load.",
    },
    # ---- posterior chain ----
    {
        "name": "Cable Hip Thrust",
        "category": "posterior_chain",
        "target_muscle": "glutes",
        "equipment": "cable or barbell",
        "default_sets": 3,
        "default_reps": 10,
        "progression_notes": "Add load once full lockout with a posterior pelvic tilt is consistent.",
        "injury_notes": "Generally safe with knee injuries (no knee flexion under load); avoid with acute hip flexor strain.",
        "description": "Glute strength, strong carryover to cycling power output.",
    },
    {
        "name": "Glute Bridge",
        "category": "posterior_chain",
        "target_muscle": "glutes, hamstrings",
        "equipment": "none or barbell",
        "default_sets": 3,
        "default_reps": 12,
        "progression_notes": "Progress to single-leg before adding barbell load.",
        "injury_notes": "Low spinal load — safe starting point returning from most lower-back or hip injuries.",
        "description": "Glute activation and strength, easy entry point for rehab.",
    },
    {
        "name": "Back Extension",
        "category": "posterior_chain",
        "target_muscle": "lower back, glutes, hamstrings",
        "equipment": "hyperextension bench",
        "default_sets": 3,
        "default_reps": 12,
        "progression_notes": "Progress hold/tempo before adding a weight plate to the chest.",
        "injury_notes": "Avoid with acute lower-back pain; reintroduce gradually once pain-free at rest.",
        "description": "Posterior chain endurance and lower-back strength.",
    },
    # ---- mobility ----
    {
        "name": "90/90 Hip Mobility",
        "category": "mobility",
        "target_muscle": "hips",
        "equipment": "none",
        "default_sets": 2,
        "default_reps": None,
        "progression_notes": "Progress range and control before adding a loaded hold.",
        "injury_notes": "Safe with most hip/knee injuries at low intensity; skip if it directly reproduces knee pain.",
        "description": "Hip internal/external rotation mobility, useful for cycling position and general hip health.",
    },
    {
        "name": "Couch Stretch",
        "category": "mobility",
        "target_muscle": "hip flexors, quads",
        "equipment": "wall or bench",
        "default_sets": 2,
        "default_reps": None,
        "progression_notes": "Progress depth/duration gradually, not load.",
        "injury_notes": "Ease in gently with acute knee pain — reduce knee flexion depth.",
        "description": "Hip flexor/quad length, counters cycling's flexed-hip posture.",
    },
    {
        "name": "Thoracic Spine Rotation",
        "category": "mobility",
        "target_muscle": "thoracic spine",
        "equipment": "none",
        "default_sets": 2,
        "default_reps": 10,
        "progression_notes": "Progress range of motion, not speed.",
        "injury_notes": "Safe with most injuries — low load, controlled movement.",
        "description": "Upper-back rotation mobility, supports cycling aero position and general posture.",
    },
]


class Command(BaseCommand):
    help = "Load / update the exercise library."

    def handle(self, *args, **options):
        created = updated = 0
        for e in EXERCISES:
            _, was_created = Exercise.objects.update_or_create(
                name=e["name"],
                defaults={
                    "category": e["category"],
                    "target_muscle": e["target_muscle"],
                    "equipment": e["equipment"],
                    "default_sets": e["default_sets"],
                    "default_reps": e["default_reps"],
                    "progression_notes": e["progression_notes"],
                    "injury_notes": e["injury_notes"],
                    "description": e["description"],
                },
            )
            created += was_created
            updated += (not was_created)
        self.stdout.write(self.style.SUCCESS(
            f"Done. {created} created, {updated} updated, {len(EXERCISES)} total."
        ))
